if(BUILD_WITH_CONAN)
    set(CGAL "cgal")
    set(ARMADILLO "armadillo")
    set(EIGEN3 "Eigen3")
    set(SPARSEHASH "sparsehash")
    set(BLAS "BLAS")
    set(METEOIO "meteoio")
    set(GPERFTOOLS "gperftools")
    set(FUNC "func")
    set(GDAL "GDAL")
    set(TBB "TBB")
    set(GSL "gsl")
    set(NETCDFCXX "netcdf-cxx")
    set(VTK "vtk")
    set(TRILINOS "trilinos")
    set(HDF5 "HDF5")
    set(PROJ "proj")
else()
    set(CGAL "CGAL")
    set(ARMADILLO "Armadillo") #But the FindArmadillo sets ARMADILLO_INCLUDE[...]
    set(EIGEN3 "Eigen3")
    set(SPARSEHASH "Sparsehash")
    set(BLAS "BLAS")
    set(METEOIO "MeteoIO")
    set(GPERFTOOLS "Gperftools")
    set(FUNC "Func")
    set(GDAL "GDAL")
    set(TBB "TBB")
    set(GSL "GSL")
    set(NETCDFCXX "NetCDF")
    set(VTK "VTK")
    set(TRILINOS "Trilinos")
    set(HDF5 "HDF5")
    set(PROJ "PROJ")

endif()